[workspace]
publish = false
allow_dirty = false
changelog_update = true
dependencies_update = false
git_release_enable = true
publish_allow_dirty = false
semver_check = false
git_release_type = "auto"
release = false

[[package]]
name = "sn_auditor"
changelog_update = true
git_release_enable = true
release = true

[[package]]
name = "sn_build_info"
changelog_update = true
git_release_enable = false
release = true

[[package]]
name = "sn_cli"
release = true
changelog_update = true
changelog_include = [
    "sn_client",
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn_client"
release = true
changelog_update = true
git_release_enable = false
changelog_include = [
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn_faucet"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_logging"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_metrics"
release = true
changelog_update = true
git_release_enable = false


[[package]]
name = "sn_networking"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_node"
release = true
changelog_update = true
changelog_include = [
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn-node-manager"
release = true
changelog_update = true
changelog_include = [
    "sn_node",
    "sn_peers_acquisition",
    "sn_protocol",
    "sn_service_management",
    "sn_transfers",
]


[[package]]
name = "node-launchpad"
release = true
changelog_update = true
git_release_enable = true
changelog_include = ["sn_node", "sn_protocol", "sn-node-manager"]

[[package]]
name = "sn_node_rpc_client"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_peers_acquisition"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_protocol"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_registers"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_service_management"
release = true
changelog_update = true
git_release_enable = false

[[package]]
name = "sn_transfers"
release = true
changelog_update = true
git_release_enable = false
