[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = false
git_release_enable = true
publish_allow_dirty = false
semver_check = false
git_release_type = "auto"

[[package]]
name = "sn_auditor"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_build_info"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_cli"
changelog_update = true
publish = true
changelog_include = [
    "sn_client",
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn_client"
changelog_update = true
git_release_enable = false
publish = true
changelog_include = [
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn_faucet"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_logging"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_metrics"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_networking"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_node"
changelog_update = true
publish = true
changelog_include = [
    "sn_networking",
    "sn_transfers",
    "sn_registers",
    "sn_peers_acquisition",
    "sn_protocol",
]

[[package]]
name = "sn_node_launchpad"
changelog_update = true
git_release_enable = true
publish = true

[[package]]
name = "sn_node_rpc_client"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_peers_acquisition"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_protocol"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_registers"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_service_management"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "sn_transfers"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "test_utils"
changelog_update = true
git_release_enable = false
publish = false

[[package]]
name = "token_supplies"
changelog_update = true
git_release_enable = false
publish = true
