[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Node RPC Client"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node_rpc_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.6.32-rc.2"

[[bin]]
name = "safenode_rpc_client"
path = "src/main.rs"

[features]
nightly = []

[dependencies]
assert_fs = "1.0.0"
async-trait = "0.1"
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "0.6.2"
hex = "~0.4.3"
libp2p = { version = "0.54.1", features = ["kad"]}
libp2p-identity = { version="0.2.7", features = ["rand"] }
sn_build_info = { path = "../sn_build_info", version = "0.1.16-rc.2" }
sn_logging = { path = "../sn_logging", version = "0.2.37-rc.2" }
sn_node = { path = "../sn_node", version = "0.112.0-rc.2" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.5.4-rc.2" }
sn_protocol = { path = "../sn_protocol", version = "0.17.12-rc.2", features=["rpc"] }
sn_service_management = { path = "../sn_service_management", version = "0.4.0-rc.2" }
sn_transfers = { path = "../sn_transfers", version = "0.20.0-rc.2" }
thiserror = "1.0.23"
# # watch out updating this, protoc compiler needs to be installed on all build systems
# # arm builds + musl are very problematic
tonic = { version = "0.6.2" }
tokio = { version = "1.32.0", features = ["rt"] }
tokio-stream = { version = "~0.1.12" }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"

[lints]
workspace = true
