[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Record Storage"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_record_store"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.11"

[dependencies]
 libp2p = { git="https://github.com/libp2p/rust-libp2p", branch="master",  version="0.52", features = ["tokio","kad", "macros"] }
rand = { version = "~0.8.5", features = ["small_rng"] }
sn_protocol = { path = "../sn_protocol", version = "0.1.10" }
tracing = { version = "~0.1.26" }

[dev-dependencies]
quickcheck = "1.0.3"
