[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Build Info"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_build_info"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.9-alpha.1"

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "git", "gitcl"] }

[lints]
workspace = true
