[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Token Supplies"
# documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "token_supplies"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.42"


[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11", default-features=false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs-next = "2.0"
