name: Protect main and set default PR branch

on: [pull_request]

jobs:
  check-base-branch:
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          protected-branches: "main, beta"
          default-branch: "alpha"
          update-branch: true
